# Generated by Django 4.0.1 on 2022-02-23 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartOrder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, verbose_name='Order ID')),
                ('price', models.FloatField(default=0)),
                ('payment_method', models.CharField(choices=[('COD', 'COD'), ('SSLCommerz', 'SSLCommerz')], default='COD', max_length=20, verbose_name='Payment Method')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('delivery_address', models.TextField(verbose_name='Delivery Address')),
                ('delivery_time', models.DateField(auto_now_add=True, verbose_name='Delivery Time')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartOrder.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer+', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
    ]
