# Generated by Django 4.0.1 on 2022-02-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartOrder', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Delivery Address'),
        ),
    ]
