# Generated by Django 4.0.1 on 2022-02-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartOrder', '0003_order_transaction_id_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
