# Generated by Django 4.0.1 on 2022-02-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AddField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(blank=True, default='prodImage/default_prod_image.png', upload_to='prodImage'),
        ),
    ]
