# Generated by Django 4.0 on 2022-03-30 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_product_prod_img'),
        ('cartOrder', '0002_alter_cart_options_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartItem_id', models.CharField(blank=True, max_length=200)),
                ('cartItem_quantity', models.PositiveBigIntegerField(default=0)),
                ('cartItem_price', models.FloatField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartOrder.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
            options={
                'verbose_name_plural': 'Cart Items',
            },
        ),
    ]
