# Generated by Django 4.0 on 2022-03-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartOrder', '0003_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
    ]
