# Generated by Django 4.0 on 2022-03-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default='prodImage/default_img', upload_to='prodImage'),
        ),
    ]
