# Generated by Django 4.0 on 2022-03-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_options_product_prod_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(default='prodImage/default_img.png', upload_to='prodImage'),
        ),
    ]
